import nodemailer from "nodemailer"

// // app.post("/login", (req, res) => {

//     const dateTimeObject = new Date();
//     // const userName = req.body.email
//     // const emailSubject = req.body.subject

//     var emailDef = nodemailer.createTransport({
//         service: 'gmail',
//         auth: {
//             user: 'rushikeshmhetre2001@gmail.com',
//             pass: 'xxxxxxx'
//         }
//     });

//     var mailOpt = {
//         from: 'rushikeshmhetre2001@gmail.com',
//         to: 'varunraje21@gmail.com',
//         subject: 'Test Mail',
//         text: 'This is test email generated by Node Backend' + { dateTimeObject }
//     };

//     emailDef.sendMail(mailOpt, function (err, info) {
//         if (err) {
//             console.log(err)

//         } else {
//             console.log("Email send to" + { to })
//         }
//     })


// // })


let transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true, 
    auth: {
        user: 'rushimhetre2001@gmail.com', 
        pass: 'Rm@11117' 
    }
});

let mailOptions = {
    from: '"Your Name" <your_email@gmail.com>', 
    to: 'recipient_email@gmail.com', 
    subject: 'Hello', 
    text: 'Hello world?', 
    html: '<b>Hello world?</b>' 
};


transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
        return console.log(error);
    }
    console.log('Message sent: %s', info.messageId);
});
